base:
  ubuntu: "24.04"

versions:
  terraform: "latest"
  azure-cli: "latest"
  aws_cli: "latest"
  kubectl: "stable"
  helm: "latest"
  docker: "latest"
  python: "3.12"
  node: "25.6.1"
  go: "1.26.0"

user:
  name: "yolowingpixie"
  uid: 1001
  gid: 1000

docker:
  group_gid: 1001

apt_packages:
  - sudo
  - build-essential
  - curl
  - wget
  - git
  - vim
  - nano
  - neovim
  - unzip
  - jq
  - yq
  - ca-certificates
  - gnupg
  - gpg
  - apt-transport-https
  - lsb-release
  - software-properties-common
  - bash-completion

global_python_packages:
  - ruff
  - ty
  - pytest