base:
  ubuntu: "24.04"

versions:
  terraform: "latest"
  azure-cli: "latest"
  aws_cli: "latest"
  kubectl: "stable"
  helm: "latest"
  python: "3.12"
  node: "25.6.1"
  go: "1.26.0"

user:
  name: "yolowingpixie"
  uid: 1001
  gid: 1000

global_python_packages:
  - ruff
  - ty
  - pytest